# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180708_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AddField(
            model_name='videotype',
            name='little_type',
            field=models.CharField(default='', max_length=10, verbose_name='视频小类'),
        ),
    ]
