# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180708_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotype',
            name='little_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='videos.VideoType', verbose_name='视频小类'),
        ),
    ]
