# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20180708_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotype',
            name='little_type',
        ),
    ]
